-- ============================================================================
-- V069: Shopify Cross-Schema Access Setup
-- ============================================================================
-- Purpose: Grant ATTR_MGR schema access to MERCH/OMNI/VSTORE objects needed
--          for Shopify Hub and Live Publication Testing.
--
-- Two options provided:
--   Option A: GRANTS + SYNONYMS (same database - RECOMMENDED for demo)
--   Option B: DB LINKS (if schemas are on different databases)
--
-- Pattern: PAT-ORACLE-PRODUCTION-GRADE-SQL-01
-- Run as: SYS or DBA with GRANT privileges
-- ============================================================================

SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT ============================================================
PROMPT V069: Shopify Cross-Schema Access Setup
PROMPT ============================================================

-- ============================================================================
-- OPTION A: GRANTS + SYNONYMS (Same Database)
-- ============================================================================
-- This is the preferred approach for demo environments where all schemas
-- are in the same Oracle instance (e.g., DEMODB).

PROMPT
PROMPT --- STEP 1: GRANTS FROM MERCH TO ATTR_MGR ---

-- Read access to product master data
GRANT SELECT ON MERCH.STYLES TO ATTR_MGR;
GRANT SELECT ON MERCH.BARCODES TO ATTR_MGR;
GRANT SELECT ON MERCH.COLORS TO ATTR_MGR;
GRANT SELECT ON MERCH.SIZES TO ATTR_MGR;
GRANT SELECT ON MERCH.VENDORS TO ATTR_MGR;
GRANT SELECT ON MERCH.PRODUCT_TYPES TO ATTR_MGR;

-- Read/Write access to Shopify integration tables
GRANT SELECT, INSERT, UPDATE, DELETE ON MERCH.EXT_PRODUCTS TO ATTR_MGR;
GRANT SELECT, INSERT, UPDATE, DELETE ON MERCH.EXT_PRODUCT_VARIANTS TO ATTR_MGR;
GRANT SELECT ON MERCH.EXT_PRODUCTS_ACTIVITY TO ATTR_MGR;
GRANT SELECT ON MERCH.IRO_POS_EXT_PRODUCTS TO ATTR_MGR;

PROMPT --- STEP 2: GRANTS FROM OMNI TO ATTR_MGR ---

-- Read access to configuration
GRANT SELECT ON OMNI.BANNERS TO ATTR_MGR;
GRANT SELECT ON OMNI.PROVIDER_SERVICES TO ATTR_MGR;
GRANT SELECT ON OMNI.CLIENT_PARAMETERS TO ATTR_MGR;
GRANT SELECT ON OMNI.SITES TO ATTR_MGR;

-- Read access to order views
GRANT SELECT ON OMNI.V_ECOMM_ORDERS TO ATTR_MGR;
GRANT SELECT ON OMNI.V_ECOMM_ORDER_DETAILS TO ATTR_MGR;
GRANT SELECT ON OMNI.V_ECOMM_SHIPMENTS TO ATTR_MGR;
GRANT SELECT ON OMNI.V_ECOMM_CUSTOMERS TO ATTR_MGR;

-- Read access to staging tables (for monitoring)
GRANT SELECT ON OMNI.STG_ORDERS TO ATTR_MGR;
GRANT SELECT ON OMNI.STG_ORDER_DETAILS TO ATTR_MGR;

-- Execute on scheduler (if needed)
-- GRANT EXECUTE ON DBMS_SCHEDULER TO ATTR_MGR;

PROMPT --- STEP 3: GRANTS FROM VSTORE TO ATTR_MGR ---

GRANT SELECT ON VSTORE.MV_MERCHANDISE_HIERARCHY TO ATTR_MGR;
GRANT SELECT ON VSTORE.SKUINVENTORY TO ATTR_MGR;
-- GRANT EXECUTE ON VSTORE.INTFS_SHOPIFY_PK TO ATTR_MGR;  -- If direct calls needed

PROMPT --- STEP 4: CREATE SYNONYMS IN ATTR_MGR ---

-- Connect as ATTR_MGR or have CREATE SYNONYM privilege
-- These synonyms allow the backend to use simple table names

-- MERCH Synonyms
CREATE OR REPLACE SYNONYM ATTR_MGR.STYLES FOR MERCH.STYLES;
CREATE OR REPLACE SYNONYM ATTR_MGR.BARCODES FOR MERCH.BARCODES;
CREATE OR REPLACE SYNONYM ATTR_MGR.COLORS FOR MERCH.COLORS;
CREATE OR REPLACE SYNONYM ATTR_MGR.SIZES FOR MERCH.SIZES;
CREATE OR REPLACE SYNONYM ATTR_MGR.VENDORS FOR MERCH.VENDORS;
CREATE OR REPLACE SYNONYM ATTR_MGR.PRODUCT_TYPES FOR MERCH.PRODUCT_TYPES;
CREATE OR REPLACE SYNONYM ATTR_MGR.EXT_PRODUCTS FOR MERCH.EXT_PRODUCTS;
CREATE OR REPLACE SYNONYM ATTR_MGR.EXT_PRODUCT_VARIANTS FOR MERCH.EXT_PRODUCT_VARIANTS;
CREATE OR REPLACE SYNONYM ATTR_MGR.EXT_PRODUCTS_ACTIVITY FOR MERCH.EXT_PRODUCTS_ACTIVITY;
CREATE OR REPLACE SYNONYM ATTR_MGR.MERCH_EXT_PRODUCT_VARIANTS FOR MERCH.EXT_PRODUCT_VARIANTS;

-- OMNI Synonyms
CREATE OR REPLACE SYNONYM ATTR_MGR.BANNERS FOR OMNI.BANNERS;
CREATE OR REPLACE SYNONYM ATTR_MGR.PROVIDER_SERVICES FOR OMNI.PROVIDER_SERVICES;
CREATE OR REPLACE SYNONYM ATTR_MGR.CLIENT_PARAMETERS FOR OMNI.CLIENT_PARAMETERS;
CREATE OR REPLACE SYNONYM ATTR_MGR.SITES FOR OMNI.SITES;
CREATE OR REPLACE SYNONYM ATTR_MGR.V_ECOMM_ORDERS FOR OMNI.V_ECOMM_ORDERS;
CREATE OR REPLACE SYNONYM ATTR_MGR.V_ECOMM_ORDER_DETAILS FOR OMNI.V_ECOMM_ORDER_DETAILS;
CREATE OR REPLACE SYNONYM ATTR_MGR.V_ECOMM_SHIPMENTS FOR OMNI.V_ECOMM_SHIPMENTS;
CREATE OR REPLACE SYNONYM ATTR_MGR.V_ECOMM_CUSTOMERS FOR OMNI.V_ECOMM_CUSTOMERS;
CREATE OR REPLACE SYNONYM ATTR_MGR.STG_ORDERS FOR OMNI.STG_ORDERS;

-- VSTORE Synonyms
CREATE OR REPLACE SYNONYM ATTR_MGR.MV_MERCHANDISE_HIERARCHY FOR VSTORE.MV_MERCHANDISE_HIERARCHY;
CREATE OR REPLACE SYNONYM ATTR_MGR.SKUINVENTORY FOR VSTORE.SKUINVENTORY;

PROMPT
PROMPT ============================================================
PROMPT OPTION A COMPLETE: Grants and Synonyms created.
PROMPT ============================================================

-- ============================================================================
-- OPTION B: DB LINKS (Different Databases)
-- ============================================================================
-- Uncomment this section if MERCH/OMNI/VSTORE are on a different database.
-- Replace connection strings with your actual TNS names or connect descriptors.

/*
PROMPT
PROMPT --- OPTION B: Creating Database Links ---

-- DB Link to MERCH database
CREATE DATABASE LINK MERCH_LNK
CONNECT TO merch_read IDENTIFIED BY "your_password"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=merch-db.example.com)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=MERCHDB)))';

-- DB Link to OMNI database
CREATE DATABASE LINK OMNI_LNK
CONNECT TO omni_read IDENTIFIED BY "your_password"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=omni-db.example.com)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=OMNIDB)))';

-- DB Link to VSTORE database
CREATE DATABASE LINK VSTORE_LNK
CONNECT TO vstore_read IDENTIFIED BY "your_password"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=vstore-db.example.com)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=VSTOREDB)))';

-- Create synonyms pointing to remote tables via DB link
CREATE OR REPLACE SYNONYM ATTR_MGR.STYLES FOR MERCH.STYLES@MERCH_LNK;
CREATE OR REPLACE SYNONYM ATTR_MGR.EXT_PRODUCTS FOR MERCH.EXT_PRODUCTS@MERCH_LNK;
CREATE OR REPLACE SYNONYM ATTR_MGR.EXT_PRODUCT_VARIANTS FOR MERCH.EXT_PRODUCT_VARIANTS@MERCH_LNK;
CREATE OR REPLACE SYNONYM ATTR_MGR.BANNERS FOR OMNI.BANNERS@OMNI_LNK;
CREATE OR REPLACE SYNONYM ATTR_MGR.PROVIDER_SERVICES FOR OMNI.PROVIDER_SERVICES@OMNI_LNK;
CREATE OR REPLACE SYNONYM ATTR_MGR.V_ECOMM_ORDERS FOR OMNI.V_ECOMM_ORDERS@OMNI_LNK;
CREATE OR REPLACE SYNONYM ATTR_MGR.MV_MERCHANDISE_HIERARCHY FOR VSTORE.MV_MERCHANDISE_HIERARCHY@VSTORE_LNK;

PROMPT --- OPTION B COMPLETE: Database Links and Synonyms created ---
*/

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

PROMPT
PROMPT --- Verifying Access ---

-- Test MERCH access
SELECT 'MERCH.STYLES' as OBJECT, COUNT(*) as ROW_COUNT FROM MERCH.STYLES WHERE ROWNUM <= 1;
SELECT 'MERCH.EXT_PRODUCTS' as OBJECT, COUNT(*) as ROW_COUNT FROM MERCH.EXT_PRODUCTS;

-- Test OMNI access
SELECT 'OMNI.BANNERS' as OBJECT, COUNT(*) as ROW_COUNT FROM OMNI.BANNERS;
SELECT 'OMNI.PROVIDER_SERVICES (Shopify)' as OBJECT, COUNT(*) as ROW_COUNT FROM OMNI.PROVIDER_SERVICES WHERE PROVIDER_ID LIKE 'SHOPIFY%';

-- Test VSTORE access
SELECT 'VSTORE.MV_MERCHANDISE_HIERARCHY' as OBJECT, COUNT(*) as ROW_COUNT FROM VSTORE.MV_MERCHANDISE_HIERARCHY WHERE ROWNUM <= 1;

PROMPT
PROMPT ============================================================
PROMPT V069 COMPLETE
PROMPT 
PROMPT Next Steps:
PROMPT 1. Restart FarsightIQ backend to pick up new access
PROMPT 2. Run: POST /api/shopify/test/publish with a style_id
PROMPT ============================================================

COMMIT;
